apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: do-eks
  version: "1.21"
  region: us-east-1

availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.9.1-eksbuild.1

managedNodeGroups:
  - name: p4d-24xlarge
    instanceType: p4d.24xlarge
    instancePrefix: p4d-efa
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    labels: { processor: gpu, gpu: A100 }
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
  - name: p3dn-24xlarge
    instanceType: p3dn.24xlarge
    instancePrefix: p3dn-efa
    privateNetworking: true
    availabilityZones: ["us-east-1b"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 0
    maxSize: 10
    volumeSize: 900
    labels: { processor: gpu, gpu: V100 }
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        fsx: true
        cloudWatch: true
  
