apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: simnet-mpi
spec:
  slotsPerWorker: 8
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          restartPolicy: OnFailure
          containers:
          - image: ************.dkr.ecr.us-east-1.amazonaws.com/simnet:21.06-efa
            imagePullPolicy: Always
            name: simnet-mpi-launcher
            env:
             - name: NCCL_DEBUG
               value: INFO
            workingDir: /data/examples/ldc
            command:
            - mpirun
            - --allow-run-as-root
            - -np
            - "16"
            - -N
            - "8"
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - NCCL_ALGO=Ring
            - -x
            - FI_PROVIDER=efa
            - -x
            - FI_EFA_USE_DEVICE_RDMA=1
            - -x
            - RDMAV_FORK_SAFE=1
            - -x
            - NCCL_DEBUG
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openlib
            - python
            - ldc_2d.py
    Worker:
      replicas: 2
      template:
        spec:
          nodeSelector:
            beta.kubernetes.io/instance-type: p3dn.24xlarge
            #beta.kubernetes.io/instance-type: p4d.24xlarge
          containers:
          - image: ************.dkr.ecr.us-east-1.amazonaws.com/simnet:21.06-efa
            workingDir: /data/examples/ldc
            imagePullPolicy: Always
            name: simnet-mpi-worker
            resources:
              limits:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
                vpc.amazonaws.com/efa: 1
                memory: 80000Mi
              requests:
                nvidia.com/gpu: 8
                hugepages-2Mi: 5120Mi
                vpc.amazonaws.com/efa: 1
                memory: 80000Mi
            volumeMounts:
            - name: persistent-storage
              mountPath: /data
          volumes:
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: fsx-claim
